# Generated by Django 4.1.2 on 2022-11-01 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_adventure_created_at_adventure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
