# Generated by Django 4.1.2 on 2022-11-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_alter_adventure_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='date',
            field=models.TextField(),
        ),
    ]
