# Generated by Django 4.1.2 on 2022-10-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_adventure_possession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adventure',
        ),
        migrations.DeleteModel(
            name='Possession',
        ),
    ]
